branches:
  only:
    - master
language: node_js
node_js:
  - lts/*
cache: yarn
before_script: npm install -g pm2
script: yarn build
after_success:
  - echo "${DEPLOY_KEY}" | base64 --decode > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H ${DEPLOY_HOST} >> ~/.ssh/known_hosts
  - ssh-keyscan -H ${DEPLOY_HOST_TEST} >> ~/.ssh/known_hosts
  - rsync -a -e ssh build/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}
  - pm2 deploy production
